### ISSUE TITLE
Development environments using fig

### ISSUE THREAD

**Issue by diasjorge** [barcelona-js/barcelonajs.org#55]
---
level: beginner
language: en
twitter: @dias_jorge
tags:
  - docker
  - fig

---

Jorge Dias, Software Engineer turned Devops @ Xing, responsible for development and testing environments is going to talk about the research being done at Xing regarding the use of docker and will do a brief overview of working with fig and some custom tools to improve the workflow

**Comment by diasjorge** [comment]
Hey guys do you think this could be relevant for the group?

**Comment by PatrickHeneise** [comment]
Absolutely.
