### ISSUE TITLE
Arquillian loves JavaScript too.

### ISSUE THREAD

**Issue by lordofthejars** [barcelona-js/barcelonajs.org#57]
---
level: advanced
language: es
twitter:  @alexsotob
tags:
  - angularjs
  - testing
  - arquillian
  - javaee 

---

Nowadays a lot of applications are being developed not using a single language but more than one. 
One of the most used paradigm is implementing the front-end using Html + JavaScript (for example with AngularJs) and implementing the back-end with Java.

There is a lot of test frameworks for Javascipt code and the same for Java, but if you want to test system wide in an automatic way it seems that you need some kind of glue to meet both worlds.
 
Come to this session to learn how Arquillian can help you on writing tests for these applications.

**Comment by villanopack** [comment]
+1

**Comment by lordofthejars** [comment]
If you think it has more sense to be done in english, there is no problem

**Comment by aslakknutsen** [comment]
+1

**Comment by lfryc** [comment]
+1

**Comment by vguardiola** [comment]
+1

**Comment by PatrickHeneise** [comment]
Do you want to give this talk on the next event?

**Comment by lordofthejars** [comment]
do you think it may be possible to schedule for April?

**Comment by PatrickHeneise** [comment]
Sure. I'll leave it open.

**Comment by gmoretti** [comment]
+1

**Comment by PatrickHeneise** [comment]
@lordofthejars you're up for next week?!

**Comment by eth0lo** [comment]
@lordofthejars are you coming next week?

**Comment by lordofthejars** [comment]
I have answered an email about this maybe they have not shared with you
where I commented that currently I am so busy writing a book about
Arquillian and also a lot of work on JSR374 spec. I said that because I
would really like to talk in your community, how about on May 20th?

Alex.

El dj., 16 abr., 2015 a les 19:36, Jean Carlos Meninno (<
notifications@github.com>) va escriure:

**Comment by PatrickHeneise** [comment]
I'd love to have this this month, if any way possible, not to postpone it forever.

**Comment by lordofthejars** [comment]
This month is quite impossible for this reason I said to fix a date on May
20th so I can plan to organize my schedule to fit this.

El dj., 16 abr., 2015 a les 20:38, Patrick Heneise (<
notifications@github.com>) va escriure:

**Comment by PatrickHeneise** [comment]
May it is then.

**Comment by lordofthejars** [comment]
We meet on 20th May isn't it? What time and where?

**Comment by eth0lo** [comment]
19:30 at mobile world center

**Comment by PatrickHeneise** [comment]
@lordofthejars It's May 19, not 20.

**Comment by lordofthejars** [comment]
ok, initially we talked about 20th but I think it is not a problem at all.


El dt., 5 maig 2015 a les 14:19, Patrick Heneise (<notifications@github.com>)
va escriure:

**Comment by lordofthejars** [comment]
:)
