### ISSUE TITLE
Ionic 101

### ISSUE THREAD

**Issue by vampaynani** [barcelona-js/barcelonajs.org#58]
---
level: beginner
language: es
twitter: vampaynani
tags:
  - ionic framework
  - angularjs

---

An introduction to this friendly angular framework to build great hybrid apps with web technologies you already know and love.

**Comment by vguardiola** [comment]
+1

**Comment by davesnx** [comment]
+1

**Comment by PatrickHeneise** [comment]
Speaker isn't in Barcelona.
