### ISSUE TITLE
jQuery plugin for better HTML file inputs

### ISSUE THREAD

**Issue by mparramont** [barcelona-js/barcelonajs.org#59]
level: beginner
language: en
twitter: mparramon
tags:
  - jQuery
  - TDD
  - Jasmine

Have you ever wanted to style an HTML file input in a easy way? I did, so I took [this guide](quirksmode.org/dom/inputfile.html) And turned it into a [jQuery plugin](plugins.jquery.com/enhancedfileinput/). [Here are some slides](http://www.developingandstuff.com/2013/01/jquery-plugin-for-better-html-file.html) I made for colognejs.de about developing it with Jasmine specs.

**Comment by mparramont** [comment]
WTF I just found out I'm giving this talk tomorrow :O next time notify me somehow please :)

**Comment by PatrickHeneise** [comment]
Apologies. Next time we'll post a comment.
