### ISSUE TITLE
Developing mobile web apps for the real world with Ionic Framework

### ISSUE THREAD

**Issue by danicomas** [barcelona-js/barcelonajs.org#60]
---
level: advanced
language: es
twitter: @dcomasf
tags:
  - angularjs
  - ionicframework

---

It is well-known that develop in Android and iOS is a hardest task. For many companies the cost of develop and maintain two parallel environments is very expensive, and of course for a logic reason it isn't  a good approach. At present, Many solutions exist to solve this, PhoneGap, Xamarin, the recent but only introduced ReactJS Native and of course Ionic.

In this speech I will show how it works with some demos and the pros and cons about to use Ionic to develop web mobile apps for the real world.

**Comment by eth0lo** [comment]
+1

**Comment by PatrickHeneise** [comment]
cool. BarcelonaJS March is alright for you?

**Comment by danicomas** [comment]
It is perfect @PatrickHeneise

**Comment by PatrickHeneise** [comment]
Great, see you then!

**Comment by sleistner** [comment]
+1
