### ISSUE TITLE
Introduction to React.js

### ISSUE THREAD

**Issue by ustun** [barcelona-js/barcelonajs.org#61]
---
level: beginner
language: en
twitter: ustunozgur
tags:
  - reactjs
  - ui frameworks

---

Building UI's is hard, but JavaScript is not to blame. Facebook's open source UI library React.js introduces a sane solution to building UI's, based on
uni-directional flow and components with clear interfaces. Although object oriented in appeareance, React builds itself on a functional programming
basis, making programs written by this library easy to develop and reason about. 

In this talk, we will go over the founding principles of this exciting library which has been steadily gaining popularity since it was first introduced in May 2013. 
We will also briefly talk about accompanying technologies such as Flux, immutablejs and react-router.

**Comment by PatrickHeneise** [comment]
Which one would you give this month? React or ECMA?

**Comment by ustun** [comment]
Hi Patrick, I would prefer React as that seems to be more exciting, the ECMA one is a list of new features; but if you already had a session on React, then I can give the ECMA one too.

**Comment by PatrickHeneise** [comment]
Awesome, thanks!

**Comment by ustun** [comment]
Thank you too, see you there. 

Btw, I'm going to be staying in Barcelona for the whole month with my friend.  Do you have any recommendations for co-working spaces in the area? We are in the Born area. 

Thank you very much. You can email me at ustun@ustunozgur.com

**Comment by gmoretti** [comment]
+1
