### ISSUE TITLE
Introduction to EcmaScript 6

### ISSUE THREAD

**Issue by ustun** [barcelona-js/barcelonajs.org#62]
---
level: beginner/intermediate
language: en
twitter: ustunozgur
tags:
  - ecmascript 6
  - javascript next

---

EcmaScript 6 is the newest and greatest of JavaScript, marking the most exciting release to date. It introduces let, const keywords, syntax for making
class'es, promises and generators, arrow functions, modules, destructuring and a bunch of other exciting features. What is more, we don't have to wait till browsers implement
ES6 features, we can start using ES6 thanks to transpilers such as Babel and Traceur projects. In this talk we will go over the most important changes coming with ES6 
and how you can start using them in your projects right now.

**Comment by ustun** [comment]
I'll not be in Barcelona next month, but this is a good topic, someone should do it.  I have the slides at https://github.com/ustun/ecmascript6-presentation if anyone is interested.

**Comment by PatrickHeneise** [comment]
Thanks!
