### ISSUE TITLE
jqComponents - Components for jQuery

### ISSUE THREAD

**Issue by jjenkov** [barcelona-js/barcelonajs.org#64]
---
level: advanced 
language: en
twitter: @jjenkov
tags:
  - jQuery
  - UI components

---

jqComponents - Structure and UI Components for jQuery

jqComponents (http://jqcomponents.com) is a small, open source toolkit / framework that brings structure and UI components to your jQuery powered web apps. 

jQuery is incredibly flexible, powerful and easy to use. But - jQuery doesn't standardize how to structure bigger apps. Therefore:

1) The app code tends to become very DOM-centric (partly because of how jQuery plugins work).
2) The app code tends to become unstructured - looking like one, big main method

jqComponents is designed to solve both of these problems, by providing a standardized way to divide your code into components and modules. Inside both of these, you can use the power of jQuery freely. 

jqComponents comes with a set of standard UI components, so you don't have to build everything from scratch. You can create a custom build of jqComponents from the project website, so you don't need to include more than you actually use.

jqComponents started as a hobby project of mine, but has now gone through 11 releases (in 2014), and will go through some this year too. I will be using it in several different projects this year.

This talk is not intended to be a complete "how to use jqComponents" talk. Rather, it will explain the reasoning behind its internal design. I am sharing this with the JS community to get your feedback. Is this a useful model? Is it flawed? How does it compare to e.g. Web Components etc. Let's get a discussion going.

**Comment by danicomas** [comment]
I haven't heard about that but sounds interesting... @jjenkov

**Comment by jjenkov** [comment]
@danicomas No, it's my framework - that is why you haven't heard much about it :-)  I know the interest among JS developers might be limited. But - you can keep this suggestion for a JS meeting where you cannot find two talks. Then I can fill up the otherwise wasted slot.

**Comment by PatrickHeneise** [comment]
Sounds interesting :+1:

**Comment by danicomas** [comment]
Nice! +1

**Comment by eth0lo** [comment]
@jjenkov can you do it next week?

**Comment by jjenkov** [comment]
@eth0lo What day would that be?

... I probably could, but it would be a more adhoc session.

**Comment by PatrickHeneise** [comment]
Tuesday 21

**Comment by jjenkov** [comment]
@PatrickHeneise Tuesday is too soon for me. I have a deadline monday evening, and it will take all my time, and possibly part of tuesday too.

**Comment by PatrickHeneise** [comment]
May it is then.

**Comment by jjenkov** [comment]
@PatrickHeneise May can work for me.

**Comment by PatrickHeneise** [comment]
Great!

**Comment by PatrickHeneise** [comment]
@jjenkov confirmed for May 19?

**Comment by jjenkov** [comment]
May 19 is fine!


On Fri, May 8, 2015 at 12:01 PM, Patrick Heneise <notifications@github.com>
wrote:

> @jjenkov <https://github.com/jjenkov> confirmed for May 19?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barcelona-js/barcelonajs.org/issues/64#issuecomment-100180444>
> .
>



-- 
Jakob Jenkov
jakob@jenkov.com
Founder, CEO

Jenkov Aps
http://jenkov.com
http://tutorials.jenkov.com

http://feeds2.feedburner.com/jenkov-com

**Comment by PatrickHeneise** [comment]
Thanks! Please update the 2015.json file with resources (git/slides/code/...)
