### ISSUE TITLE
Qumram Analytics

### ISSUE THREAD

**Issue by leonkyr** [barcelona-js/barcelonajs.org#69]
---
level: advanced 
language: en
twitter: @distributedLeo
tags:
  - angularJS, nodeJS, vanilaJS

---

Qumram.com provides capabilities to track user behaviour and replay user interaction as a movie, so I can shortly describe architecture, technologies and a few lesson learnt things.

20th of May is a good date.

**Comment by PatrickHeneise** [comment]
@leonkyr it's May 19

**Comment by leonkyr** [comment]
OK. 19th is also fine, 1 week will be enough to prepare

**Comment by PatrickHeneise** [comment]
Thanks! Please update the 2015.json file with resources (git/slides/code/...)

**Comment by leonkyr** [comment]
I tried, I don't have permission..
www.slideshare.net/PaladinPayments/20150519-qumram-barcelonajs

**Comment by PatrickHeneise** [comment]
Fork it and to a pull request please ;)
